{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sleep-service.configMapName" . }}
  labels:
    {{- include "sleep-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
