{{- if and .Values.secrets.create (not .Values.sealedSecrets.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sleep-service.secretName" . }}
  labels:
    {{- include "sleep-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
