{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sleep-service.fullname" . }}
  labels:
    {{- include "sleep-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sleep-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
{{- end }}

