# =============================================================================
# Analysis Service Helm Chart Values
# =============================================================================

# =============================================================================
# 이미지 설정
# =============================================================================
image:
  repository: octacloud/analysis-service
  tag: "latest"
  pullPolicy: IfNotPresent

# =============================================================================
# 서비스 설정
# =============================================================================
service:
  type: ClusterIP
  port: 8080
  targetPort: 8000

# =============================================================================
# 배포 설정
# =============================================================================
replicaCount: 1

# =============================================================================
# 리소스 설정
# =============================================================================
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# =============================================================================
# 헬스 체크 설정
# =============================================================================
livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5
  timeoutSeconds: 10

# =============================================================================
# 환경 변수 설정
# =============================================================================
env:
  REDIS_HOST: "10.226.34.155"
  REDIS_PORT: "6379"
  PYTHONUNBUFFERED: "1"

# =============================================================================
# 서비스 계정 설정
# =============================================================================
serviceAccount:
  create: true
  name: ""

# =============================================================================
# ConfigMap 설정
# =============================================================================
configMap:
  create: true
  name: ""

# =============================================================================
# Secret 설정
# =============================================================================
secrets:
  create: false
  name: ""

# =============================================================================
# Ingress 설정
# =============================================================================
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ""
      paths:
        - path: /api/analysis(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

# =============================================================================
# 노드 선택자
# =============================================================================
nodeSelector: {}

# =============================================================================
# 톨러레이션
# =============================================================================
tolerations: []

# =============================================================================
# 어피니티
# =============================================================================
affinity: {}

# =============================================================================
# 추가 설정
# =============================================================================
podAnnotations: {}

podSecurityContext: {}
securityContext: {}
imagePullSecrets: []
autoscaling:
  enabled: false
lifecycle: {}

