{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: grafana
    component: config
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/grafana
    serve_from_sub_path = true
    
    [security]
    admin_user = {{ .Values.grafana.admin.user }}
    admin_password = {{ .Values.grafana.admin.password }}
    
    [users]
    allow_sign_up = false
    
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    
    [datasources]
    default = loki
    
    [log]
    mode = console
    level = info

    [dashboards]
    default_home_dashboard_path = /etc/grafana/dashboards/home-dashboard.json
    
    [provisioning]
    datasources = /etc/grafana/provisioning/datasources
    dashboards = /etc/grafana/provisioning/dashboards

  datasources.yaml: |
    apiVersion: 1
    
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: true
        editable: true
        
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir:9009
        editable: true
        
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: false
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: 'mimir'
            tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
            queries:
              - name: 'Sample query'
                query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
          serviceMap:
            datasourceUid: 'mimir'
          search:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: 'loki'

  dashboards.yaml: |
    apiVersion: 1
    
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /etc/grafana/dashboards

  home-dashboard.json: |
    {
      "id": null,
      "uid": "home-overview",
      "title": "Observability Overview",
      "timezone": "browser",
      "schemaVersion": 38,
      "version": 1,
      "refresh": "30s",
      "time": { "from": "now-1h", "to": "now" },
      "panels": [
        {
          "type": "logs",
          "title": "Recent Logs (Loki)",
          "datasource": { "type": "loki", "uid": "P8E80F9AEF21F6940" },
          "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
          "targets": [ { "expr": "{namespace=\"microservices-dev\"}" } ]
        },
        {
          "type": "timeseries",
          "title": "CPU Usage (example)",
          "datasource": { "type": "prometheus", "uid": "PAE45454D0EDB9216" },
          "gridPos": { "x": 0, "y": 10, "w": 24, "h": 8 },
          "fieldConfig": { "defaults": {}, "overrides": [] },
          "targets": [ { "expr": "up" } ]
        }
      ]
    }

  lgtm-overview-dashboard.json: |
    {
      "id": null,
      "uid": "lgtm-overview",
      "title": "LGTM Stack Overview",
      "tags": ["lgtm", "monitoring", "overview"],
      "timezone": "browser",
      "schemaVersion": 38,
      "version": 1,
      "refresh": "30s",
      "time": { "from": "now-1h", "to": "now" },
      "panels": [
        {
          "id": 1,
          "title": "System Overview",
          "type": "stat",
          "targets": [
            {
              "expr": "up",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "thresholds": {
                "steps": [
                  {
                    "color": "red",
                    "value": 0
                  },
                  {
                    "color": "green",
                    "value": 1
                  }
                ]
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "Pod Status",
          "type": "table",
          "targets": [
            {
              "expr": "kube_pod_status_phase",
              "refId": "A",
              "format": "table"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "CPU Usage",
          "type": "timeseries",
          "targets": [
            {
              "expr": "rate(container_cpu_usage_seconds_total[5m]) * 100",
              "refId": "A",
              "legendFormat": "{{`{{pod}}`}}"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          }
        },
        {
          "id": 4,
          "title": "Memory Usage",
          "type": "timeseries",
          "targets": [
            {
              "expr": "container_memory_usage_bytes / 1024 / 1024",
              "refId": "A",
              "legendFormat": "{{`{{pod}}`}}"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          }
        }
      ]
    }

  microservices-dashboard.json: |
    {
      "id": null,
      "uid": "microservices-monitoring",
      "title": "Microservices Monitoring",
      "tags": ["microservices", "kubernetes", "monitoring"],
      "timezone": "browser",
      "schemaVersion": 38,
      "version": 1,
      "refresh": "30s",
      "time": { "from": "now-1h", "to": "now" },
      "panels": [
        {
          "id": 1,
          "title": "Service Health",
          "type": "stat",
          "targets": [
            {
              "expr": "up{job=~\".*-service\"}",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "thresholds": {
                "steps": [
                  {
                    "color": "red",
                    "value": 0
                  },
                  {
                    "color": "green",
                    "value": 1
                  }
                ]
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 6,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "HTTP Request Rate",
          "type": "timeseries",
          "targets": [
            {
              "expr": "rate(http_requests_total[5m])",
              "refId": "A",
              "legendFormat": "{{`{{service}}`}}"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 6,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "HTTP Response Time",
          "type": "timeseries",
          "targets": [
            {
              "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
              "refId": "A",
              "legendFormat": "{{`{{service}}`}} p95"
            },
            {
              "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))",
              "refId": "B",
              "legendFormat": "{{`{{service}}`}} p50"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 18,
            "y": 0
          }
        }
      ]
    }

  analysis-service-dashboard.json: |
    {
      "id": null,
      "uid": "analysis-service-monitoring",
      "title": "Analysis Service Monitoring",
      "tags": ["analysis-service", "brainwave", "kafka"],
      "timezone": "browser",
      "schemaVersion": 38,
      "version": 1,
      "refresh": "30s",
      "time": { "from": "now-1h", "to": "now" },
      "panels": [
        {
          "id": 1,
          "title": "Analysis Service Health",
          "type": "stat",
          "targets": [
            {
              "expr": "up{job=\"analysis-service\"}",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "thresholds": {
                "steps": [
                  {
                    "color": "red",
                    "value": 0
                  },
                  {
                    "color": "green",
                    "value": 1
                  }
                ]
              }
            }
          },
          "gridPos": {
            "h": 6,
            "w": 6,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "Brainwave Analysis Rate",
          "type": "stat",
          "targets": [
            {
              "expr": "rate(brainwave_analysis_total[5m])",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "short"
            }
          },
          "gridPos": {
            "h": 6,
            "w": 6,
            "x": 6,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "Kafka Consumer Status",
          "type": "stat",
          "targets": [
            {
              "expr": "kafka_consumer_connected",
              "refId": "A"
            }
          ],
          "gridPos": {
            "h": 6,
            "w": 6,
            "x": 12,
            "y": 0
          }
        },
        {
          "id": 4,
          "title": "Database Connections",
          "type": "stat",
          "targets": [
            {
              "expr": "mysql_connections_active",
              "refId": "A"
            }
          ],
          "gridPos": {
            "h": 6,
            "w": 6,
            "x": 18,
            "y": 0
          }
        }
      ]
    }
{{- end }}
