{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace.name }}
  labels:
    app: loki
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      component: server
  template:
    metadata:
      labels:
        app: loki
        component: server
    spec:
      containers:
      - name: loki
        image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
        imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9096
          name: grpc
        args:
        - -config.file=/etc/loki/loki.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
        resources:
          {{- toYaml .Values.loki.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 45
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        {{- if .Values.loki.persistence.enabled }}
        persistentVolumeClaim:
          claimName: loki-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
