{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace.name }}
  labels:
    app: loki
    component: server
spec:
  type: {{ .Values.loki.service.type }}
  ports:
  - port: {{ .Values.loki.service.port }}
    targetPort: 3100
    protocol: TCP
    name: http
  - port: 9096
    targetPort: 9096
    protocol: TCP
    name: grpc
  selector:
    app: loki
    component: server
{{- end }}
