{{- if .Values.mimir.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: {{ .Values.namespace.name }}
  labels:
    app: mimir
    component: server
spec:
  type: {{ .Values.mimir.service.type }}
  ports:
  - port: {{ .Values.mimir.service.port }}
    targetPort: 9009
    protocol: TCP
    name: http
  - port: 9095
    targetPort: 9095
    protocol: TCP
    name: grpc
  selector:
    app: mimir
    component: server
{{- end }}
