{{- if .Values.mimir.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: {{ .Values.namespace.name }}
  labels:
    app: mimir
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
      component: server
  template:
    metadata:
      labels:
        app: mimir
        component: server
    spec:
      containers:
      - name: mimir
        image: "{{ .Values.mimir.image.repository }}:{{ .Values.mimir.image.tag }}"
        imagePullPolicy: {{ .Values.mimir.image.pullPolicy }}
        ports:
        - containerPort: 9009
          name: http
        - containerPort: 9095
          name: grpc
        args:
        - -config.file=/etc/mimir/mimir.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/mimir
        - name: storage
          mountPath: /tmp/mimir
        resources:
          {{- toYaml .Values.mimir.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /ready
            port: 9009
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /ready
            port: 9009
          initialDelaySeconds: 60
      volumes:
      - name: config
        configMap:
          name: mimir-config
      - name: storage
        {{- if .Values.mimir.persistence.enabled }}
        persistentVolumeClaim:
          claimName: mimir-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
