{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace.name }}
  labels:
    app: tempo
    component: server
spec:
  type: {{ .Values.tempo.service.type }}
  ports:
  - port: {{ .Values.tempo.service.port }}
    targetPort: 3200
    protocol: TCP
    name: http
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: jaeger
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  selector:
    app: tempo
    component: server
{{- end }}
