prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true

grafana:
  enabled: true
  adminPassword: admin123
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  service:
    type: ClusterIP
    port: 3000
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      analysis-service-dashboard:
        file: dashboards/analysis-service-dashboard.json
      sleep-service-dashboard:
        file: dashboards/sleep-service-dashboard.json
      auth-service-dashboard:
        file: dashboards/auth-service-dashboard.json
      user-service-dashboard:
        file: dashboards/user-service-dashboard.json
      saga-orchestration-service-dashboard:
        file: dashboards/saga-orchestration-service-dashboard.json
      overview-dashboard:
        file: dashboards/overview-dashboard.json
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: monitoring.mong.live
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: monitoring-tls
        hosts:
          - monitoring.mong.live
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/use-regex: "true"

# Prometheus ServiceMonitor for auto-discovery
serviceMonitor:
  enabled: true
  namespace: microservices-dev
