{{- if .Values.blueGreen.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: analysis-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  args:
  - name: service-name
  metrics:
  - name: http-health-check
    interval: 10s
    count: 3
    successCondition: result == 200
    failureLimit: 1
    provider:
      web:
        url: http://{{`{{args.service-name}}`}}/health
        timeoutSeconds: 5
{{- end }}


