{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "analysis-service.secretName" . }}
  labels:
    {{- include "analysis-service.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecrets.encryptedData }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ include "analysis-service.secretName" . }}
      labels:
        {{- include "analysis-service.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
