{{- if .Values.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "analysis-service.fullname" . }}-active
  labels:
    {{- include "analysis-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: active
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "analysis-service.selectorLabels" . | nindent 4 }}
    rollouts-pod-template-hash: "{{ .Values.blueGreen.activeHash | default "active" }}"
{{- end }}
