prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true

grafana:
  enabled: true
  adminPassword: admin123
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: monitoring.mong.live
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: monitoring-tls
        hosts:
          - monitoring.mong.live
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/use-regex: "true"

# Prometheus ServiceMonitor for auto-discovery
serviceMonitor:
  enabled: true
  namespace: microservices-dev
