apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-configmap
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE | quote }}
  RDB_URL: {{ .Values.config.RDB_URL | quote }}
  RDB_USERNAME: {{ .Values.config.RDB_USERNAME | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.REDIS_PORT | quote }}
  SMTP_HOST: {{ .Values.config.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.config.SMTP_PORT | quote }}
