{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
  smtp-username: {{ .Values.secrets.smtpUsername | b64enc }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc }}
{{- end }}
