apiVersion: v2
name: lgtm-stack
description: A Helm chart for LGTM Stack (Loki, Grafana, Tempo, Mimir)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - observability
  - monitoring
  - logging
  - tracing
  - metrics
home: https://grafana.com/
sources:
  - https://github.com/grafana/loki
  - https://github.com/grafana/grafana
  - https://github.com/grafana/tempo
  - https://github.com/grafana/mimir
maintainers:
  - name: KEA Project
    email: dev@kea-project.com
