# =============================================================================
# LGTM Stack Helm Chart Values
# =============================================================================

# =============================================================================
# Loki (로그 수집) 설정
# =============================================================================
loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: "2.9.0"
    pullPolicy: IfNotPresent
  
  # 리소스 설정
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  # 스토리지 설정
  storage:
    type: filesystem
    filesystem:
      directory: /loki/chunks
  
  # 서비스 설정
  service:
    type: ClusterIP
    port: 3100
  
  # PVC 설정
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard
    suffix: "v2"

# =============================================================================
# Grafana (시각화) 설정
# =============================================================================
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "10.1.0"
    pullPolicy: IfNotPresent
  
  # 리소스 설정
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  # 서비스 설정
  service:
    type: ClusterIP
    port: 3000
  
  # PVC 설정
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard
  
  # 관리자 계정 설정
  admin:
    user: admin
    password: admin123
  
  # 데이터소스 설정
  datasources:
    loki:
      url: http://loki:3100
    tempo:
      url: http://tempo:3200
    mimir:
      url: http://mimir:9009

# =============================================================================
# Tempo (분산 추적) 설정
# =============================================================================
tempo:
  enabled: true
  image:
    repository: grafana/tempo
    tag: "2.1.0"
    pullPolicy: IfNotPresent
  
  # 리소스 설정
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  # 서비스 설정
  service:
    type: ClusterIP
    port: 3200
  
  # PVC 설정
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard

# =============================================================================
# Mimir (메트릭 저장) 설정
# =============================================================================
mimir:
  enabled: true
  image:
    repository: grafana/mimir
    tag: "2.9.0"
    pullPolicy: IfNotPresent
  
  # 리소스 설정
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  
  # 서비스 설정
  service:
    type: ClusterIP
    port: 9009
  
  # PVC 설정
  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard

# =============================================================================
# Ingress 설정
# =============================================================================
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: "monitoring.mong.live"
      paths:
        - path: /grafana
          pathType: Prefix
          service: grafana
          port: 3000
        - path: /loki
          pathType: Prefix
          service: loki
          port: 3100
        - path: /tempo
          pathType: Prefix
          service: tempo
          port: 3200
        - path: /mimir
          pathType: Prefix
          service: mimir
          port: 9009
  # SSL 인증서 설정 (mong.live 도메인)
  tls:
    - secretName: monitoring-tls
      hosts:
        - "monitoring.mong.live"

# =============================================================================
# 네임스페이스 설정
# =============================================================================
namespace:
  name: monitoring
  create: true
