# =============================================================================
# Swagger UI Helm Chart Values
# =============================================================================

# =============================================================================
# 이미지 설정
# =============================================================================
image:
  repository: swaggerapi/swagger-ui
  tag: "v5.9.0"
  pullPolicy: IfNotPresent

# =============================================================================
# 서비스 설정
# =============================================================================
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# =============================================================================
# 배포 설정
# =============================================================================
replicaCount: 1

# =============================================================================
# 리소스 설정
# =============================================================================
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# =============================================================================
# 환경 변수 설정
# =============================================================================
env:
  SWAGGER_JSON: "/swagger-config.json"

# =============================================================================
# ConfigMap 설정 (Swagger 설정 파일)
# =============================================================================
configMap:
  create: true
  name: "swagger-ui-config"
  data:
    swagger-config.json: |
      {
        "urls": [
          {
            "name": "User Service",
            "url": "/api/users/v3/api-docs"
          },
          {
            "name": "Sleep Service", 
            "url": "/api/sleep/v3/api-docs"
          }
        ]
      }

# =============================================================================
# Ingress 설정
# =============================================================================
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mong-develop.com
      paths:
        - path: /swagger-ui
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls: []

# =============================================================================
# 추가 설정
# =============================================================================
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
imagePullSecrets: []
