replicaCount: 1
image:
  repository: asia-northeast3-docker.pkg.dev/mong-gcp/microservices/user-service
  tag: c12e1a42ba9f2a2a4118b5cfc1058e4373881d98-17878476161
  pullPolicy: IfNotPresent
fullnameOverride: "user-service"
service:
  port: 8080
# dependency:
#   mysql:
#     service_name: "mong-gcp:asia-northeast3:microservices-mysql"
#     port: 3306
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
config:
  SPRING_PROFILES_ACTIVE: "dev"
  RDB_URL: "jdbc:mysql://10.3.202.113:3306/mong?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"
  RDB_USERNAME: "root"
  REDIS_HOST: "10.3.191.17"
  REDIS_PORT: "6379"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
